import 'package:flutter/material.dart';

const kPrimaryColor = Color(0xFF061A60);
const kSecondaryColor = Color(0xFFEC2813);
const kNeutralColor = Color(0xFF1A2731);
const kSuccessColor = Color(0xFFD1FFD0);
const kBlueShadeColor = Color(0xFF4067F2);

const kTextPrimaryColor = Color(0xFF171717);
const kTextViewBorderColor = Color(0xFF7A9DB8);
const kBackgroundFillColor = Color(0xFFF6F5FA);
const kIconContainerColor = Color(0xFFE7E7F9);
const kErrorColor = Color(0xFFFF1E05);
const kLeadingIconColor = Color(0xFF171717);
const kEventCenterLocationColor = Color(0xFF2F2F30);
const kCenterAvailableTextColor = Color(0xFF028F18);
const kCenterAvailableIndicatorColor = Color(0xFFD0FFD5);
const kCenterNotAvailableTextColor = Color(0xFFEC2813);
const kCenterNotAvailableIndicatorColor = Color(0xFFFFD5D0);
const kWhiteShadeColor = Color(0xFFF6F6F6);
const kNotificationIconColor = Color(0XFF0D34BF);
const kNotificationCheckText = Color(0XFF636262);
const kcardBackgroundColor = Color(0XFF030336);
const kGreyShadeColor = Color(0XFF87898B);
const kFilterBottomSheetDividerColor = Color(0xFFB1C2FF);
const kFilterBottomSheetLabelColor = Color(0xFF8F8F8F);
const kProfileCardColor = Color(0xFFEDECEC);
const kTabBarTitleColor = Color(0xFFC4C4C4);
const kLightBlueColor = Color(0xFFA1B6FF);
const kReviewStarRatingsColor = Color(0xFFFDCC0D);
